### PR TITLE
Support for p2pk addresses

### PR DESCRIPTION
**Pull request by willgriffin**
For your consideration, here's how I've managed to get the address from p2pk scripts. I added getAddress and getAddressString methods to the TransactionOutput mostly because I'm not confident enough about what's going on throughout the library to muck with existing methods.

### CODE REVIEW

**Comment by afk11** [comment]
I am road tripping today, but I'll get to it later when I get back!

I haven't ran into p2pk addresses much, guessing they are long and unsightly? :-)

No objections to the new feature, just not sure about the additions to TransactionOutput.. Just seems that extra coupling could be avoided since AddressFactory can create it for you, and its a property of the script that determines the address..

Only other thing would be a quick test, and I'm just a little unsure on the mechanics of this older address type - should we remove/rename the getHash function for semantic reasons?

**Comment by afk11** [comment]
Hmm, dynamic exception might be causing tests to fail, I have @expectedExceptionMessage in there

**Comment by willgriffin** [comment]
TBH I didn't know much of anything about the different types of scripts before I had to figure out why the library wasn't giving me the same one I was seeing from everywhere else for the first blocks ;) It turns out p2pk were the norm in the beginning so I needed support for them to parse the blockchain from genesis.  I don't expect they'll show up much at all going forward. 

I think the main reason I just added a new method to TransactionOutput was the Script->getAddress method uses 'fromScript' whereas I needed 'fromOutputScript' and didn't feel right changing it not fully understanding what/why there was a difference. I suspect fromScript *may* be redundant, but I wasn't sure enough to mess about until I had time to more fully grok the library.  

Whoops on the failing tests, I had it in my head they were related to something other than my changes  which of course was wrong.

**Comment by willgriffin** [comment]
I just noticed the AddressFactory::fromString bit and modified it now so I wouldn't forget, but I haven't had time to play around with testing it yet. I'll come back to it later today, I'm not expecting this will get merged until you're back at work anyways :)

**Comment by afk11** [comment]
Just back this evening, I've been looking over this! Yeah the different script types at play is interesting. There were some weird ones that forked still-running 0.6 clients for months and months.. Blockchain thought the same transaction had been mined like 30 times since it appeared in orphaned blocks, but technically the tx was what invalidated the block from newer clients.... Some strange stuff happens!

I've been trying to work this out, I'm really sure pay-to-pubkey has an address.. I am looking at it now, and don't see any reference to addresses being used to represent public keys, only the public key hash. 

Taken from https://www.blocktrail.com/BTC/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16 - the address 12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S does correspond to the public key `04ae1a62fe09c5f51b13905f07f06b99a2f7159b2225f374cd378d71302fa28414e7aab37397f554a7df5f142c21c1b7303b8a0626f1baded5c72a704f7e6cd84c` 

There is no address type (see the prefixes) which produces a pay-to-pubkey script, so I am not sure it would be called an Address.. This seems to be a shortcut which works by still being redeemable by the public key regardless of whether you chose pay-to-pubkey or pay-to-pubkey-hash, but it's not an address. 

I notice that blockexplorer, blocktrail, and bitcoin core indeed all take advantage of this, but strictly speaking, pay-to-pubkey doesn't have an address. 

I could be nit picking, but I'm hesitant to add it, since it's only for convenience and not strictly correct. That said - @rubensayshi might be a good one to ask, since he's behind blocktrail and might give us his reasoning for it :)

**Comment by willgriffin** [comment]
I must confess I have no idea what you're talking about when it comes to what's considered an 'address'. I'm just trying to get results consistent with everything else so I can avoid writing a raw block parser myself ;) 

In the gitter chat @rubensayshi seemed to think that getScript()->getAddress() should work, but it didn't for the earlier addresses although there was pre-existing functionality for recognizing them (see OutputClassifier). I suspect the better thing to do would be something like change the Script::getAddress method to use AddressFactory::fromOutputScript - although that doesn't seem right as a Script may not be an OutputScript(?). 

Anyways, I got the results I was looking for and am able to move forward now with my fork so if this patch is inappropriate feel free to close and I'll just continue hacking at my own fork as I need (at this point i'm onto fun with multisigs). Or, if there's any changes I should make so it's more palatable just let me know.

**Comment by afk11** [comment]
I'll be hanging on gitter - talk to you there when you're on! 

Oh, you should try playing with the blk000x.dat files! If you loaded one of them into Parser you might be able to sync against the files instead of the rpc! BitWasp\Bitcoin\Serializer\Block\HexBlockSerializer::fromParser would work. 

I'm not sure if there are other things in there, like the Block network message which wraps the usual block structure, but it'd be an interesting experiment. Syncing against the RPC can be quite slow

**Comment by willgriffin** [comment]
any verdict on this? i'd much rather prefer to be using the main branch and am finding little things on my explorations through the blockchain. i'm in the gitter chat if you want me to make adjustments

**Comment by willgriffin** [comment]
closing this and resetting my fork to implement different changes as discussed in chat

**Pull request closed without merging**
