### PR TITLE
Viacoin: [Network] bech32

### PR DESCRIPTION
**Pull request by romanornr**
Currently being used in Vialectrum and soon in Viacoin Core, ledger & trezor.

### CODE REVIEW

**Comment by afk11** [comment]
Nice! Wanna make two quick PR's, one targeting the 0.0.34 branch (currently released one), and one targeting 0.0.35 (next one, and has nice stuff)

**Comment by afk11** [comment]
There are some padding/spacing errors in the test files, which caused travis to fail.

**Comment by romanornr** [comment]
Thanks, just fixed the padding. Travis CI tests are passing now.

**Comment by afk11** [comment]
Awesome, cheers! I mentioned those other branches as master is quite a bit away from being tagged, but I can tag 0.0.34 today and 0.0.35 soon.

**Pull request merged**
