### PR TITLE
v0.0.7: Fix versions in composer.json

### PR DESCRIPTION
**Pull request by afk11**
Ping @josecelano

You may as well check this works before I merge, by adding the following to your composer.json and changing the required version from `v0.0.7` to `v0.0.7-fix-phpecc`. Once that works I'll make an official tag

    "repositories": [  
          {  
              "type": "vcs",  
              "url": "https://github.com/afk11/bitcoin-php"  
          }  
      ],  

Background: https://github.com/Bit-Wasp/bitcoin-php/issues/381

### CODE REVIEW

**Comment by afk11** [comment]
@josecelano did you test if this solves your problem? I ask because I fixed _all_ the packages in this way it might have side-effects for your own packages. Can you please check in case there's a problem after I merge?

**Comment by josecelano** [comment]
@afk11 It seems to work, thank you!!

**Comment by emabusi** [comment]
@afk11 Wouldn't it be better to add a  new class with the old name called Gmp and that is a child of the new named class (GmpMath) to allow backward compatibility?

**Comment by afk11** [comment]
@emabusi since 0.0.7 users already technically upgraded to mdanter/ecc 0.4? That mightn't be unreasonable, and I might consider it if blockcypher haven't yet fixed at 0.0.7.1. Had you begun using stuff from mdanter/ecc: 0.3.1? Or do you happen to be signing transactions, and it's slowed down a lot? 

I'm not sure entirely it's worth maintaining 0.0.7 much, at this point I'd recommend adopting a later version, so I'd like to understand the case first.

**Comment by InspiredPrynce** [comment]
None of this things seem to work for me at the moment...

"blockcypher/php-client": "^1.5",

"name": "mdanter/ecc",
            "version": "v0.5.0",
            "source": {
                "type": "git",
                "url": "https://github.com/phpecc/phpecc.git",
                "reference": "ed5c6d496f5310de1b7071b8375fafa3559a1344"
            },

"name": "bitwasp/bitcoin",
            "version": "v0.0.7",
            "source": {
                "type": "git",
                "url": "https://github.com/Bit-Wasp/bitcoin-php.git",
                "reference": "7316b7bc5fc204d972e5df3b2485366ee4cd1a18"
            },

Help me please

**Comment by afk11** [comment]
v0.0.7 is way to old for that.. You should look at what version blockcypher is using and try to follow that one.

**Comment by InspiredPrynce** [comment]
>composer require blockcypher/php-client

Using version ^1.5 for blockcypher/php-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 26 installs, 0 updates, 0 removals
  - Installing rgooding/protobuf-php (0.0.1): Loading from cache
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing evenement/evenement (v2.1.0): Loading from cache
  - Installing react/stream (v0.4.6): Loading from cache
  - Installing react/event-loop (v0.4.3): Loading from cache
  - Installing react/promise-timer (v1.2.0): Loading from cache
  - Installing react/dns (v0.4.11): Loading from cache
  - Installing react/socket (v0.4.6): Loading from cache
  - Installing react/cache (v0.4.1): Loading from cache
  - Installing react/socket-client (v0.4.6): Loading from cache
  - Installing pleonasm/merkle-tree (1.0.0): Loading from cache
  - Installing fguillot/json-rpc (v0.0.1): Loading from cache
  - Installing bitwasp/stratum (v0.1.0): Loading from cache
  - Installing rych/hash_pbkdf2-compat (v1.0.1): Loading from cache
  - Installing ringcentral/psr7 (1.2.1): Loading from cache
  - Installing react/http (v0.4.4): Loading from cache
  - Installing react/http-client (v0.4.17): Loading from cache
  - Installing react/child-process (v0.4.3): Loading from cache
  - Installing react/react (v0.4.2): Loading from cache
  - Installing fgrosse/phpasn1 (2.0.0): Loading from cache
  - Installing mdanter/ecc (v0.5.0): Loading from cache
  - Installing lastguest/murmurhash (1.3.0): Loading from cache
  - Installing doctrine/cache (v1.6.2): Loading from cache
  - Installing bitwasp/buffertools (v0.4.1): Loading from cache
  - Installing bitwasp/bitcoin (v0.0.7): Loading from cache
  - Installing blockcypher/php-client (v1.5.0): Loading from cache
react/event-loop suggests installing ext-libevent (>=0.1.0)

This is what i get when i install blockcypher

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/7316b7bc5fc204d972e5df3b2485366ee4cd1a18/composer.json#L30

bitcoin-php v0.0.7 is meant to track mdanter/ecc v0.3.x but the wrong version constraint was used in that tag, so composer is rolling along to 0.4, and 0.5.... blockcypher should fix it for all their users though.. 0.0.7 is ancient for this library :)

Test a fix by putting `"mdanter/ecc": "v0.3.x"` into your composer.json and reinstalling. If it works, submit a pull request to blockcyphers repo with that same version, and it should be fixed for everyone.

**Comment by InspiredPrynce** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove blockcypher/php-client v1.5.0
    - bitwasp/buffertools v0.4.1 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.4.0 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.8 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.7 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.6 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.5 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.4 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.3 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.2 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3.1 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - bitwasp/buffertools v0.3 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with your
 requirements or minimum-stability.
    - bitwasp/buffertools v0.2.1 requires afk11/ecc ~0.0.2 -> no matching package found.
    - bitwasp/buffertools v0.2 requires afk11/ecc ~0.0.2 -> no matching package found.
    - bitwasp/buffertools v0.1.3 requires mdanter/ecc dev-master -> satisfiable by mdanter/ecc[dev-master] but these conflict with your requirements or minimum-stability.
    - bitwasp/buffertools v0.1.2 requires mdanter/ecc dev-master -> satisfiable by mdanter/ecc[dev-master] but these conflict with your requirements or minimum-stability.
    - bitwasp/buffertools v0.1.1 requires mdanter/ecc dev-master -> satisfiable by mdanter/ecc[dev-master] but these conflict with your requirements or minimum-stability.
    - bitwasp/buffertools v0.1.0 requires mdanter/ecc dev-master -> satisfiable by mdanter/ecc[dev-master] but these conflict with your requirements or minimum-stability.
    - bitwasp/buffertools v0.4.1 requires mdanter/ecc ~0.4 -> satisfiable by mdanter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.5.0] but these conflict with yo
ur requirements or minimum-stability.
    - Installation request for blockcypher/php-client ^1.5 -> satisfiable by blockcypher/php-client[v1.5.0].
    - blockcypher/php-client v1.5.0 requires bitwasp/bitcoin 0.0.7.* -> satisfiable by bitwasp/bitcoin[v0.0.7, v0.0.7.1].
    - bitwasp/bitcoin v0.0.7 requires bitwasp/buffertools ~0.1 -> satisfiable by bitwasp/buffertools[v0.4.1, v0.1.0, v0.1.1, v0.1.10, v0.1.11, v0.1.12, v0.1.13, v0.1.14, v0.1.15, v0.
1.16, v0.1.17, v0.1.2, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.1.8, v0.1.9, v0.2, v0.2.1, v0.3, v0.3.1, v0.3.2, v0.3.3, v0.3.4, v0.3.5, v0.3.6, v0.3.7, v0.3.8, v0.4.0].
    - bitwasp/bitcoin v0.0.7 requires bitwasp/buffertools ~0.1 -> satisfiable by bitwasp/buffertools[v0.4.1, v0.1.0, v0.1.1, v0.1.10, v0.1.11, v0.1.12, v0.1.13, v0.1.14, v0.1.15, v0.
1.16, v0.1.17, v0.1.2, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.1.8, v0.1.9, v0.2, v0.2.1, v0.3, v0.3.1, v0.3.2, v0.3.3, v0.3.4, v0.3.5, v0.3.6, v0.3.7, v0.3.8, v0.4.0].
    - bitwasp/buffertools v0.1.10 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.11 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.12 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.13 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.14 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.15 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.16 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.17 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.4 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.5 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.6 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.7 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.8 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/buffertools v0.1.9 requires mdanter/ecc 0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - bitwasp/bitcoin v0.0.7.1 requires mdanter/ecc v0.3.0 -> satisfiable by mdanter/ecc[v0.3.0].
    - Conclusion: don't install mdanter/ecc v0.3.0

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Pull request merged**
