### PR TITLE
add boolean check if address valid

### PR DESCRIPTION
**Pull request by nmarley**
Because sometimes you just need to know if an address is valid or not.

### CODE REVIEW

**Comment by afk11** [comment]
Sorry I'm only getting to this now! ACK, but needs a phpcbf pass:
`vendor/bin/phpcbf -n --standard=PSR1,PSR2 src tests`

**Comment by afk11** [comment]
Reviewing now to see why the secp256k1 stuff exploded, as nothing has changed there!

**Comment by afk11** [comment]
Resubmitted to test after fixing the secp256k1 issue, and ran a cbf pass. All checked out: #271

**Comment by nmarley** [comment]
Awesome, thanks!

**Pull request merged**
