### PR TITLE
use seperated bitwasp/buffertools

### PR DESCRIPTION
**Pull request by rubensayshi**
should tag a version on `bitwasp/buffertools` before merging this.

### CODE REVIEW

**Comment by afk11** [comment]
Nice! Maybe we can merge this, and I can rebase my large messing around over those changes, have a WIP which makes Hash:: and Base58:: only accept/return buffers, when dealing with hex/binary

**Comment by rubensayshi** [comment]
ah that sounds great, I didn't knew you had a big mess around xD

figuring out why travis and scrutinizer are being anoying, should have it solved soon

**Comment by rubensayshi** [comment]
also, is there a tagged version of phpecc we can use instead of dev-master?

**Comment by afk11** [comment]
Not right now- 0.2.0 doesn't include the most recent changes, and I think I have some tests to fix before that..

**Pull request merged**
